AWSTemplateFormatVersion: "2010-09-09"
Description: Static website hosting bucket
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: standard-wb-27
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
