name: My github actions workflow
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"
      - name: Display repo name
        run: echo "This workflow is running in ${{github.repository}}"
        # path: github_actions/.github/main.yaml
